name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Detekt
        run: ./gradlew app:assembleDebug :SharedCode:linkdebugFrameworkIosX64 backend:jar jvmTest jsBrowser